import React from 'react';
class Privacy extends React.Component {
  render() {
    return (
      <div className="main-content">
        <div className="terms-container">
          <div className="et_pb_column">
            <div className="terms_text">
              <div className="et_pb_text_inner">
                <h1><strong>PRIVACY POLICY</strong></h1>
                <p><em className="italic-text"><strong >Effective Date: November 2, 2017</strong></em></p>
                <p>&nbsp;</p>
                <p><strong>Introduction.</strong><strong>&nbsp;</strong>Corl Financial Technologies Inc. (“<strong>Corl</strong>“, “<strong>Company</strong>“, “<strong>our</strong>“, “<strong>us</strong>”&nbsp;or “<strong>we</strong>“) takes steps intended to meet privacy principles and requirements under applicable privacy legislation with respect to personal information. Personal information is information about an identifiable individual, as more particularly described under applicable privacy legislation. This Privacy Policy describes how Corl collects and uses the personal information you provide, or provided on your behalf, or which may be generated or collected when you interact with our website <a href="https://corl.io">www.corl.io</a>. It also describes the choices available to you regarding the use of, your access to, and how to update and correct your personal information. does not apply to information about our employees or to information that is not personal information.</p>
                <p><strong>Personal Information We Collect.&nbsp;</strong>Corl and its agents and representatives collect personal information about you from various sources (including, without limitation, from credit reporting agencies, creditors, and businesses and financial institutions with which you have had a financial relationship).</p>
                <p>Personal information we collect includes, without limitation:</p>
                <ul>
                  <li>your name, address, e-mail address, Internet Protocol address, telephone number, date of birth, and other contact information;</li>
                  <li>your business name, address, tax id number, business inception date, business bank statements (and data about your banking transactions),&nbsp;telephone number and address;</li>
                  <li>financial information, such as your bank name and your bank account number, personal and business credit bureau reports, payment behavior, and other reports concerning your credit history and experience;</li>
                  <li>other financial or personal information about you, such as your percent ownership in the business, your liabilities, and your financial condition;</li>
                  <li>your social insurance number;</li>
                  <li>your identity through an acceptable form of government issued identification;</li>
                  <li>we may collect data through a third party site inspection vendor, or social media sites or services.</li>
                  <li>information about any previous loan applications you may have previously applied for (directly or on your behalf), and any previous Corl loan payment history;</li>
                  <li>such other information we may collect with your consent or as permitted or required by applicable law; and</li>
                  <li>personal information about you given to us by others and personal information about others provided by you.</li>
                </ul>
                <p><strong>Use of Personal Information. We generally use personal information for the following purposes:</strong></p>
                <ul>
                  <li>to verify your identity in connection with our user registration process;</li>
                  <li>to manage and administer your account with Corl;</li>
                  <li>to facilitate the transactional process between financial institutions</li>
                  <li>to compile and analyze information to better understand our customers</li>
                  <li>to determine your Corl Score and risk grade, revenue based financing rate, revenue based financing cap, term and maximum loan amount;</li>
                  <li>to set up auto payment deductions as may be required by our loan agreements</li>
                  <li>to produce data analytics and reports containing summaries of data and general information that we may share with business partners.</li>
                  <li>to prevent fraud, identity theft or illegal activities;</li>
                  <li>to maintain our business records for reasonable periods and to generally manage and administer our business;</li>
                  <li>to resolve disputes and to enforce our loan agreements;</li>
                  <li>to compare information for accuracy and verify it with third parties; and</li>
                  <li>to meet legal, regulatory, insurance, audit, processing and security requirements imposed on us, which may include establishing and verifying your identity and checking your identity against money laundering, terrorist financing or similar watch lists established by regulatory agencies or similar bodies in the United States and/or Canada.</li>
                </ul>
                <p>We may also use your personal information in other manners with your consent or as permitted or required by applicable law.</p>
                <p>We reserve the right to disclose your personal&nbsp;information as required by law, such as to comply with a judicial proceeding, court order, or legal process served on our Web site&nbsp;when we believe that disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or respond to a government request.</p>
                <p><strong>Disclosure of Your Personal Information.&nbsp;</strong>We may disclose your personal information to our affiliates for internal audit, management, billing or administrative purposes. In addition, we may disclose your personal information in the following circumstances:</p>
                <p><strong>Service Providers.&nbsp;</strong>We may disclose personal information to outside agents, representatives and service providers (including affiliates of Corl&nbsp;acting in this capacity) that perform services on our behalf, such as website systems operators, credit reporting agencies, banks and collection agencies, law firms or otherwise to collect, use, disclose, store or process personal information on our behalf for the purposes described in this Privacy Policy. We take reasonable steps to ensure that personal information we disclose to these outside agents, representatives and service providers is protected and not used or further disclosed for purposes other than as directed by us or as required by applicable law.</p>
                <p><strong>Legal, Regulatory, Etc.&nbsp;</strong>We may disclose your personal information as necessary to meet applicable legal, regulatory, industry self-regulatory, insurance, audit and security requirements and obligations, including as required by our outside agents, representatives and service providers.</p>
                <p><strong>Business Transactions.&nbsp;</strong>Personal information may be used by us and disclosed to third parties in connection with certain business transactions, including, without limitation, in connection with a proposed or actual financing of Corl&nbsp;or a sale, assignment or other disposal of all or part of our business or assets. In that case, personal information may be disclosed to third parties for the purpose of, among others, evaluating and consummating the proposed transaction, or fulfilling reporting, due diligence, inspection or audit requirements or obligations to those parties. Assignees or successors of Corl Financial Technologies Inc.&nbsp;or any part of our business or assets may use and disclose your personal information for similar purposes as those described in this Privacy Policy. You will be notified via email and/or a notice on our website, of any change in ownership, uses of your personal information, and choices you may have regarding your personal information.</p>
                <p><strong>General.&nbsp;</strong>We may otherwise disclose your personal information only in ways that are described in this privacy policy and with your consent or as permitted or required by applicable law.</p>
                <p><strong>The Internet and Our Website.&nbsp;</strong>We operate and control our website at&nbsp;<a href="https://corl.io">Corl</a>.</p>
                <p><strong>Tracking Technologies.&nbsp;</strong>We and our partners, affiliates, or analytics or service providers, use technologies such as cookies, beacons, tags, and scripts, to analyze trends, administer the website, tracking users’ movements around the website, and to gather demographic information about our user base as a whole. We may receive reports based on the use of these technologies by these companies on an individual and aggregated basis.</p>
                <p>We may use “cookie” files to enhance the use of our website and the loan marketplace for our registered users and other users. A “<strong>cookie</strong>”&nbsp;is a small text file placed on a computer’s hard drive by our web page server in order to recognize that a user has previously visited our website and to apply the configuration preferences that the user has chosen. Other than the information provided by a user, cookie files do not contain information that can be used to identify an individual user. You can disable cookies using your Internet browser’s settings and you should consult your browser’s help function for information on how to disable cookies. Please note that if you disable cookies, certain features of our website may not function properly. We do not require anyone to accept cookies in order to use our website or the loan marketplace.</p>
                <p>The use of cookies by our tracking utility company and service providers is not covered by our privacy policy. We do not have access or control over these cookies. Our tracking utility company and service providers use session ID cookies to make it easier for you to view your business address, and provide us with usage tracking for the platform.</p>
                <p>Third parties with whom we partner to provide certain features on our website or to display advertising based upon your web browsing activity use HTML5 to collect and store information. Various browsers may offer their own management tools for removing HTML5.</p>
                <p>As is true of most websites, we gather certain information automatically and store it in log files. This information may include Internet protocol (IP) addresses, browser type, internet service provider (ISP), referring/exit pages, operating system, date/time stamp, and/or clickstream data.</p>
                <p>We may combine this automatically collected log information with other information we collect about you. We do this to improve services we offer you, analytics, and site functionality.</p>
                <p><strong>E-mail Policy.&nbsp;</strong>Once you complete our user registration and your Corl account is created, we will use your e-mail address as one method to contact you regarding your Corl account. We may also contact you at any telephone number, or physical or electronic address to collect and may include SMS messages (including text messages), calls using prerecorded messages or artificial voice, and calls and messages delivered using auto telephone dialing system or an automatic texting system. Automated messages may be played when the telephone is answered, whether by you or someone else. In the event that an agent or representative calls, he or she may also leave a message on your answering machine, voice mail, or send one via text. In order to provide consistent and high-quality registered user service and support, we may store any correspondence with you in a file specific to you. Furthermore, we will use your e-mail address to provide you with e-mail updates regarding changes to our Privacy Policy and changes.</p>
                <p><strong>No Third-Party Marketers.&nbsp;</strong>We do not sell, rent or trade your personal information to third parties or marketing firms for their promotional purposes. We do send communications periodically to inform you of the status of transactions or events related to your Corl account and your use of our website. Some of these communications are required in connection with transactions you are considering or have concluded through the Corl website. Receiving emails from our website is part of our service. If you no longer wish to receive these emails, you may opt out of them by unsubscribing or by contacting Customer Service.</p>
                <p><strong>Your Consent.&nbsp;</strong>Your consent to the collection, use and disclosure of personal information may be given in various ways. Your consent can be express (e.g., orally, electronically or on a form you may sign describing the intended uses and disclosures of personal information) or implied (e.g., when you provide information necessary for a service or transaction you have requested). In certain circumstances, you may provide your consent where notice has been provided to you regarding our intended use of your personal information and you have not withdrawn your consent for the intended use (e.g., when you do not elect an “<strong>opt-out</strong>”&nbsp;option). Your consent may also be given by your authorized representative, such as your legal guardian or a person having a power of attorney.</p>
                <p><strong>Generally, by providing us with your personal information, we will assume that you consent to our collection, use and disclosure of such information for the purposes identified or described in this Privacy Policy, if applicable, or otherwise at the time of collection.</strong></p>
                <p>We collect, use and disclose your personal information with your consent, except as permitted or required by applicable law. We may be required or permitted under certain statutes or regulations to collect, use or disclose personal information without your consent, including, without limitation, to comply with a court order, local or federal regulations or a legally permitted inquiry by a government or law enforcement agency, or to collect a debt owed to us, our agents, representatives and service providers, or another registered user.</p>
                <p><strong>Security.&nbsp;</strong>We take reasonable steps to protect your personal information using physical, electronic or procedural security measures appropriate to the sensitivity of the information in our custody or control, which may include secure web pages, encryption, password intrusion detection systems and firewalls as described below. If you have any questions about the security of your personal information, you can contact us via our <a href="https://corl.io/contact">Contact Us</a> page.</p>
                <p><strong>Secure Web Pages.&nbsp;</strong>All of the pages on our website that ask for your personal information are transferred to your browser through HTTPS, a secure server communications protocol. You can verify this encryption by checking for the lock icon on your browser. If your browser’s security feature has been turned on, a pop up box will notify you when you enter a secure page.</p>
                <p><strong>Encryption.&nbsp;</strong>When you send your personal information to us, it is protected by SSL (Secure Sockets Layer) Technology. SSL does not allow anyone to read your personal information. When you transmit your information to us, SSL encrypts it (translates the data into a string of gibberish characters) and only we can decode the encryption.</p>
                <p><strong>Firewall Protection.&nbsp;</strong>Your financial information is encrypted and backed up every day. In the unlikely event that our website is “<strong>hacked</strong>”&nbsp;your data will remain secure.</p>
                <p><strong>Password Protection.&nbsp;</strong>To retrieve information about your status as a registered user on the loan marketplace and your transactions, you are required to enter both a password and your user name.</p>
                <p>These safeguards are used to protect against loss or theft, as well as unauthorized access, disclosure, copying, use or modification of your personal information. In addition to the security features we have implemented in our systems, the security of your personal information relies on you safeguarding your password. Accordingly, you may not share your password with anyone.</p>
                <p>Our authorized employees, agents and parties to a contract of work or services with us who require access to your personal information in order to fulfill their job requirements or contracts will have access to your personal information.</p>
                <p><strong>Access, Correction and Contacting Us.&nbsp;</strong>You can access, delete or review the personal information you submit to us at any time through your Corl account. To make changes to your personal profile information, log in to your Corl account using your user name and password. Click on “<strong>My Info</strong>”&nbsp;in the “<strong>My Profile</strong>”&nbsp;section and make changes to your profile as necessary.</p>
                <p>We may establish and maintain a file of your personal information for the purposes described in this Privacy Policy, which will be accessible by you at our operational offices at 642 Rue de Courcelle, Suite PH5 Montreal, QC, H4C 3C5, Canada. You may request access to your file or correction of any inaccuracies in your personal information in our possession, or held by the personal information agent who prepared a credit report on you. Your right to access or correct your personal information is subject to applicable legal restrictions. If you wish to request access or correction of your file, cancel your account or request that we no longer use your information to provide you services, or to make inquiries or complaints or have other concerns about our personal information practices, you may e-mail us via our&nbsp;<a href="https://corl.io/contact/">Contact Us</a>&nbsp;page or write to us at the above address, Attention: Privacy Department. We will respond to your request within a reasonable timeframe.</p>
                <p><strong>Data Retention.&nbsp;</strong>We will retain your information for as long as your account is active or as needed to provide you services. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements</p>
                <p><strong>Note Regarding Children Under 18.&nbsp;</strong>Users of our website and loan marketplace must be Canadian residents that are 18 years of age or older. Additional requirements apply to registered users.</p>
                <p><strong>Helpful Tips on Protecting Your Personal Information.&nbsp;</strong>Set forth below are several tips intended to help you protect your personal information:</p>
                <p><strong>Password Protection.&nbsp;</strong>It is a good practice to select a password for your Corl account that is a unique combination of letters, numbers and symbols. Your password should not be predictable or easy to guess. A good practice is to change your password periodically, such as every 90 days.</p>
                <p><strong>Identity Theft.&nbsp;</strong>If you think your identity has been stolen, contact all three credit-reporting agencies listed below to put a fraud alert on your credit report:</p>
                <p><strong>TransUnion (</strong>www.transunion.ca<strong>)<br />
                  Fraud Victim Assistance Department</strong><br />
                  <strong>Phone: 1-800-663-9980</strong><br />
                  <strong>Mail: TransUnion P.O. Box 338, LCD1, Hamilton, Ontario, L8L7W2</strong>
                </p>
                <p><strong>Equifax (www.equifax.ca)<br />
                  Consumer Fraud Division</strong><br />
                  <strong>Phone: 1-800-465-7166</strong><br />
                  <strong>Mail: Equifax Credit Information Services, Inc P.O. Box 190 Jean Talon, Montreal, PQ, H1S2Z2</strong>
                </p>
                <p><strong>The Canadian Anti-Fraud Centre (</strong>www.antifraudcentre-centreantifraude.ca<strong>)</strong></p>
                <p>After you contact all three credit-reporting agencies, you should check your credit report again in 30 to 60 days for any new signs of identity theft or records that still need to be removed. You should also file a police report with your local enforcement agency. A police report is helpful when dealing with creditors as you challenge inquiries to your credit report or accounts opened fraudulently in your name. You should also keep records of all actions you have taken and letters you have written regarding your identity theft.</p>
                <p><strong>Customer Testimonials/Comments/Reviews</strong>. We post customer testimonials/comments/reviews on our website which may contain personal information. We do obtain the customer’s consent via email prior to posting the testimonial to post their name along with the testimonial. To request removal of your personal information from Testimonials or comments please contact us via our <a href="contact">Contact Us</a>&nbsp;page.</p>
                <p><strong>Blogs/Discussion Forums</strong>. If you use a bulletin board, chat room, blog or forum on this Web site, you should be aware that any personal information you submit there can be read, collected, or used by other users of these forums, and could be used to send you unsolicited messages. We are not responsible for the personal information you choose to submit in these forums. To request removal of your personal information from our blog or community forum, contact us via our <a href="contact">Contact Us</a>&nbsp;page. In some cases, we may not be able to remove your personal information, in which case we will let you know if we are unable to do so and why.</p>
                <p><strong>Links to Third Party Websites.</strong><strong>&nbsp;</strong>Our website includes links to other websites whose privacy practices may differ from those of Corl. If you submit personal information to any of those websites, your information is governed by their privacy policies. We encourage you to carefully read the privacy policy of any website you visit.</p>
                <p><strong>Social Media Widgets.</strong><strong>&nbsp;</strong>Our website includes Social Media Features, such as the Facebook Like button, and Widgets, such as the Share This button or interactive mini-programs that run on our website. These Features may collect your Internet protocol address, which page you are visiting on our website, and may set a cookie to enable the Feature to function properly. Social Media Features and Widgets are either hosted by a third party or hosted directly on our website. Your interactions with these Features are governed by the privacy policy of the company providing it.</p>
                <p><strong>Referrals.</strong><strong>&nbsp;</strong>If you choose to use our referral service to tell a friend about our website, we will ask you for your friend’s name and email address. We will automatically send your friend a one-time email inviting him or her to visit the website. Corl stores this information for the sole purpose of sending this one-time email and tracking the success of our referral program. Your friend may contact us via our <a href="contact">Contact Us</a>&nbsp;page to request that we remove this information from our database.</p>
                <p><strong>Changes in this Privacy Policy</strong>. We may update this privacy policy to reflect changes to our information practices. If we make any change in how we use your personal information we will notify you by email (sent to the e-mail address specified in your account) or by means of a notice on this Site prior to the change becoming effective. We encourage you to periodically review this page for the latest information on our privacy practices.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

    )
  }
}

export default Privacy;
