import React from 'react';
class Term extends React.Component {
  componentWillMount() {
    document.title = "Terms of Use | Revenue share on the blockchain | Corl";
  }
  render() {
    return (
      <div className="main-content">
        <div className="terms-container">
          <div className="et_pb_column">
            <div className="terms_text">
              <div className="et_pb_text_inner">
                <h1><strong>TERMS OF USE</strong></h1>
                <p><em><strong>Effective Date: November 2, 2017</strong></em></p>
                <p>&nbsp;</p>
                <p><strong>1. Terms of Use.&nbsp;</strong>This Terms of Use agreement (the “<strong>Terms of Use</strong>“) applies to the services offered by Corl Financial Technologies Inc. (the “<strong>Company</strong>“, “<strong>we</strong>” or “<strong>us</strong>“) through any of the Company’s Web sites, including <a href="https://corl.io/">www.corl.io</a>. Corl Financial Technologies Inc. is a Canadian corporation. When using our Services, whether it is just browsing or initiating a transaction, you are subject to the guidelines or rules currently applicable to the Services in the Legal Agreements, which may be amended from time to time. By using the Services and the Web sites, you acknowledge that you have read, understand, and agree to be bound by the Terms of Use and the Legal Agreements and to comply with all applicable laws and regulations. If you do not agree, you are not authorized to use, and should not use, the Web sites.</p>
                <p>You understand that the Company may amend or modify the Terms of Use at any time, and without notice to you. Your continued use of the Web site after any amendment or modification constitutes your agreement to the revised Terms of Use.</p>
                <p><strong>2. Limitation of Use.&nbsp;</strong>This Web site and all its contents are intended solely for your use alone. You may not reproduce, publish, transmit, distribute, display, modify, create, work from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the content design, source code, software, photos, images and other information from this Web site. The content on this Web site may be used only as a resource. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance of the content on this Web site is strictly prohibited. We reserve all intellectual property rights in all text, programs, products, processes, technology, content and other materials which appear on this Web site. Access to this Web site does not confer, nor shall such access be considered as conferring, upon anyone any license under any of these intellectual property rights. Access to this Web site does not authorize anyone to use any of the Company’s name, logo, mark or any other intellectual property in any manner, except if prior written approval is obtained.</p>
                <p>We reserve the right, in our discretion and without notice to you, to limit loan quantities, refuse orders, terminate accounts, and/or cancel orders as set forth in the Borrower Agreement or the Lender Agreement, whichever is applicable to you, if we believe that your conduct violates applicable law or is harmful to our interests.</p>
                <p><strong>3. Eligibility.&nbsp;</strong>Use of the Web site and the Services is limited to parties that lawfully can enter into and form contracts under applicable law. Without limiting the generality of the foregoing, minors may not use the Services. Every person that uses the Services represents and warrants to us that he or she is not a minor and that he or she has the capacity to enter into a binding contract. If the Services are being obtained for a business purpose, every person or entity that uses the Services represents and warrants to us that you are the authorized representative of the business with full authority to enter into a binding agreement on behalf of the business. To register, you must provide your real name, address, phone number and e-mail address, along with other information that may be required from time to time. For business purpose users, you must provide your real name, title, business address, business phone and fax numbers, and e-mail address along with other information that may be required from time to time.</p>
                <p><strong>4. Third-Parties.&nbsp;</strong>This Web site may contain hyperlinks, which will take you out of the Company’s Web site and connect you to third party sites. The Company is providing these hyperlinks to you only as a convenience. The inclusion of any hyperlink does not imply endorsement by us of the sites. These sites are not under our control and by accessing them; you do so at your own risk.</p>
                <p><strong>5. No Warranties.&nbsp;</strong>THE WEB SITE AND THE SERVICES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. CUSTOMER’S USE OF AND RELIANCE THEREON ARE AT CUSTOMER’S OWN AND SOLE RISK. WE MAKE NO OTHER REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED ON THE WEB SITE AND THE SERVICES, INCLUDING WITHOUT LIMITATION:</p>
                <p>THAT THE WEB SITE OR THE SERVICES WILL MEET YOUR REQUIREMENTS, WILL ALWAYS BE AVAILABLE, ACCESSIBLE, UNINTERRUPTED, TIMELY, SECURE OR OPERATE WITHOUT ERROR; AND</p>
                <p>ANY IMPLIED WARRANTY ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.</p>
                <p>TO THE FULL EXTENT PERMISSIBLE UNDER APPLICABLE LAW, WE DISCLAIM ANY AND ALL SUCH WARRANTIES. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, WHICH YOU OBTAIN FROM US OR THROUGH THE USE OF SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS AGREEMENT.</p>
                <p><strong>6. Limitation of Liability.&nbsp;</strong>IN NO EVENT SHALL THE COMPANY, ITS OFFICERS, DIRECTORS, AGENTS OR MANDATARIES, SUBSIDIARIES, AFFILIATES, EMPLOYEES, SUCCESSORS, ASSIGNS, CONTENT PROVIDERS OR SERVICE PROVIDERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF THIS WEB SITE OR WITH THE DELAY OR INABILITY TO USE THIS WEB SITE, OR FOR ANY INFORMATION, PRODUCTS AND SERVICES OBTAINED THROUGH THIS WEB SITE, OR OTHERWISE ARISING OUT OF THE USE OF THIS WEB SITE, WHETHER BASED ON CONTRACT, TORT, FAULT, STRICT LIABILITY OR OTHERWISE AND WHETHER OR NOT ARISING FROM THE NEGLIGENCE OF THE COMPANY.</p>
                <p><strong>7. Indemnity.&nbsp;</strong>YOU AGREE TO DEFEND, INDEMNIFY AND HOLD US AND OUR SUBSIDIARIES, PARENTS, AFFILIATES, OFFICERS, DIRECTORS, AGENTS, AND EMPLOYEES HARMLESS FROM AND AGAINST ANY AND ALL CLAIMS, LOSSES, LIABILITIES, COSTS AND EXPENSES (INCLUDING BUT NOT LIMITED TO ATTORNEYS’ FEES) ARISING FROM OR IN CONNECTION WITH (A) YOUR BREACH OF THIS AGREEMENT, AS AMENDED FROM TIME TO TIME; (B) YOUR VIOLATION OF ANY STATE, PROVINCIAL, FEDERAL, FOREIGN OR INTERNATIONAL LAWS, CODES OR REGULATIONS; AND/OR (C) YOUR VIOLATION OF ANY THIRD PARTY’S RIGHTS, INCLUDING, BUT NOT LIMITED TO, INFRINGEMENT OF ANY COPYRIGHT, VIOLATION OF ANY PROPRIETARY RIGHT AND INVASION OF ANY PRIVACY RIGHTS. THIS OBLIGATION WILL SURVIVE THE TERMINATION OF THIS AGREEMENT.</p>
                <p><strong>8. Monitoring of the Site.&nbsp;</strong>We have no duty to monitor the Web site; however, you understand and agree that we have the right to monitor the Web site electronically when we see fit and to reveal any information you provide as required or appropriate to comply with any law, regulation or other governmental request, to operate the Web site, or to shield ourselves or other users of the Web site.</p>
                <p><strong>9. Termination.&nbsp;</strong>We, in our sole discretion, unless otherwise prohibited by law, may terminate or modify this Terms of Use, access to the Web site or the Services, or any current transaction at any time without notice for any reason.</p>
                <p><strong>10. Submissions to the Web Site.&nbsp;</strong>All comments, deliberations, ideas, theories, know-how, methods, graphics or other submissions communicated to the Company through the Web site (collectively, “Submissions”) will be considered and remain the Company’s possession, and the Company is permitted to use any Submission for any purpose not prohibited by applicable law, without restriction and without compensation to the submitting party. The Company shall not be subject to any obligations of confidentiality regarding Submissions except as granted by the Company or as required by law. Before using the Web site, you should review the Company’s Privacy Policy by clicking <a href="https://corl.io/privacy">www.corl.io/privacy</a>. If you would like more information concerning the Company’s practices relating to the protection of your personal information, please contact us via our <a href="https://corl.io/contact">Contact Us</a>&nbsp;page.</p>
                <p><strong>11. Additional Terms.&nbsp;</strong>Portions of the Web site may impose, or require your agreement to, additional terms and conditions. In the event of a conflict between this Terms of Use and those additional terms and conditions, the additional terms and conditions will take precedence over the conflicting sections of this Terms of Use.</p>
                <p><strong>12. Governing Law.&nbsp;</strong>By visiting or using the Web site and/or the Services, you agree that the laws of the Province of Quebec, without regard to any principles of conflict of laws that would require or permit the application of the laws of any other jurisdiction, will govern these Terms of Use.</p>
                <p><strong>13. Language.&nbsp;</strong>The parties hereby confirm their express wish that the present Terms of Use and all documents and agreements directly and indirectly related thereto, including notices, be drawn up in English.</p>
                <p><strong className="italic-text">14. Other.&nbsp;</strong>The failure of the Company to exercise or enforce any right or provision of these Terms of Use shall not constitute a waiver of such right or provision in that or any other instance. If any provision of these Terms of Use is held invalid, the remainder of these Terms of Use shall continue in full force and effect. If any provision of these Terms of Use shall be deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms of Use and shall not affect the validity and enforceability of any remaining provisions.</p>
                <p><strong className="italic-text">15. Email Communication.&nbsp;</strong>The Company would like your express consent to send you future electronic messages (Email) to the email address you provided regarding our products and services. By becoming a user, you agree to receive emails from the Company relating to activities and products provided by Corl Financial Technologies Inc. Your consent will remain valid unless withdrawn and may be shared with third parties. Once you receive electronic messages from the Company, you will have the ability to easily and permanently unsubscribe from further electronic messages. The Company does not sell or share your information. If you have any questions regarding the Company electronic messaging policy, you may contact us at <a href="https://corl.io">www.corl.io</a>.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

    )
  }
}

export default Term;
